### PR TITLE
File expand on relative paths with pattern

### PR DESCRIPTION
**Pull request by tvoinarovskyi**
The problem:
```
⇒  neuro cp "~/Downloads/DEMO/*" storage:
Copy file:///Users/taras/Downloads/DEMO/* => storage://tvoinarovskyi/*
ERROR: cannot copy file:///Users/taras/Downloads/DEMO/* to storage://tvoinarovskyi/*: [Errno 2] No such file: '/Users/taras/Downloads/DEMO/*'
```

Added tests for _expand on file schemas too

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
I did not enable this at first place because it may conflict with path expansions in the shell. If you have a name containing `*` in your `~/Downloads/DEMO/` directory
```
neuro cp Downloads/DEMO/* storage:
```
the argument will first be expanded by the shell, and then by `neuro`.

**Comment by tvoinarovskyi** [comment]
@serhiy-storchaka I did think that was the case, but it works fine with shell expand even with the fix. It would be great to have it working in cases where we launch the command with no shell or with quoted parameters.

**Comment by serhiy-storchaka** [comment]
```
mkdir data
touch 'data/*.txt'
touch data/abc.txt
neuro -v cp data/?.txt storage:
```
Currently it only copies a single file. With your change it will copy all files.

**Comment by tvoinarovskyi** [comment]
@serhiy-storchaka Ok, I see your point. And I presume other software would also have this problem... For example:
```
taras@Tarass-MacBook-Pro:~/workspace/platform-client-python|fix_relative_pattern⚡
⇒  gsutil cp data/?.txt gs://neuro-test-gcs/
Copying file://data/abc.txt [Content-Type=text/plain]...
Copying file://data/*.txt [Content-Type=text/plain]...
/ [2 files][    0.0 B/    0.0 B]
Operation completed over 2 objects.
taras@Tarass-MacBook-Pro:~/workspace/platform-client-python|fix_relative_pattern
⇒  ls -l data/?.txt
-rw-r--r--  1 taras  staff  0 Mar 17 14:25 data/*.txt
taras@Tarass-MacBook-Pro:~/workspace/platform-client-python|fix_relative_pattern
⇒
```
Lets document the behaviour then. I feel like it's OK to state, that glob patterns will only be resolved if used in URI form.

**Comment by serhiy-storchaka** [comment]
We could also enable it on Windows where patterns are not expanded by a shell. Or use other heuristic. But I think it is safer to use a simple rule -- to expand glob patterns only in URIs. We can change it in future.

**Pull request closed without merging**
